services:
  mqtt:
      image: eclipse-mosquitto
      container_name: mqtt
      expose:
        - 1883
      ports:
        - 1883:1883
      restart: unless-stopped
      volumes:
        - ./mosquitto/config:/mosquitto/config

  chromadb:
      image:  chromadb/chroma
      container_name: chromadb
      ports:
        - 8000:8000
      restart: always
      